scene.onOverlapTile(SpriteKind.Enemy, sprites.dungeon.floorDark4, function (sprite, location) {
    desalmado.vx = 250
    animation.runImageAnimation(
    desalmado,
    [img`
        ........................
        ........................
        ........................
        ........................
        ..........fffff.........
        ........ff11111f........
        .......fb111111bf.......
        ......fbd1111111f.......
        ......fddd111111df......
        ......fdddd11111df......
        ......fddddddd11df......
        ......fddddddd111f......
        ......fddddddcf11f......
        .......fbdddb1111bf.....
        ........fffcfdb1b1f.....
        .......ffffffffbfbf.....
        ....ff.fffffffffff......
        .....ffffffff...........
        .....ffffffb1b1f........
        ......ffffffbfbf........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        `],
    500,
    true
    )
})
function avancarlevel (levelnumber: number) {
    if (levelnumber == 1) {
        tiles.setCurrentTilemap(tilemap`level1`)
        tiles.placeOnRandomTile(ameba, sprites.dungeon.collectibleInsignia)
        multilights.toggleLighting(false)
    } else if (levelnumber == 2) {
        tiles.setCurrentTilemap(tilemap`level2`)
        tiles.placeOnRandomTile(ameba, sprites.dungeon.collectibleInsignia)
        multilights.toggleLighting(true)
    } else if (levelnumber == 3) {
        tiles.setCurrentTilemap(tilemap`level2`)
        tiles.placeOnRandomTile(ameba, sprites.dungeon.collectibleBlueCrystal)
        multilights.toggleLighting(true)
    } else if (levelnumber == 4) {
        tiles.setCurrentTilemap(tilemap`level3`)
        tiles.placeOnRandomTile(ameba, sprites.dungeon.floorMixed)
        multilights.toggleLighting(false)
    } else if (levelnumber == 5) {
        tiles.setCurrentTilemap(tilemap`level4`)
        multilights.toggleLighting(false)
    } else {
    	
    }
}
scene.onOverlapTile(SpriteKind.Player, sprites.builtin.field0, function (sprite, location) {
    level_atual += 1
    avancarlevel(4)
})
scene.onOverlapTile(SpriteKind.Enemy, sprites.dungeon.floorDark1, function (sprite, location) {
    desalmado.vx = -250
    animation.runImageAnimation(
    desalmado,
    [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f1111111df.......
        ......fd1111111ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ......fd1dfbddddbf......
        ......fbddfcdbbbcf......
        .......f11111bbcf.......
        .......f1b1fffff........
        .......fbfc111bf........
        ........ff1b1bff........
        .........fbfbfff.f......
        ..........ffffffff......
        ............fffff.......
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        .........fffff..........
        ........f11111ff........
        .......fb111111bf.......
        .......f1111111dbf......
        ......fd111111dddf......
        ......fd11111ddddf......
        ......fd11dddddddf......
        ......f111dddddddf......
        ......f11fcddddddf......
        .....fb1111bdddbf.......
        .....f1b1bdfcfff........
        .....fbfbffffffff.......
        ......fffffffffff.ff....
        ...........ffffffff.....
        ........f1b1bffffff.....
        ........fbfbffffff......
        ........................
        ........................
        ........................
        ........................
        `],
    500,
    true
    )
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.hazardLava0, function (sprite, location) {
    level_atual += 2
    avancarlevel(3)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.greenOuterNorthWest, function (sprite, location) {
    level_atual += 1
    avancarlevel(5)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.chestClosed, function (sprite, location) {
    game.gameOver(true)
})
scene.onOverlapTile(SpriteKind.Enemy, sprites.dungeon.floorLight4, function (sprite, location) {
    desalmado.vy = 250
    animation.runImageAnimation(
    desalmado,
    [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111ffff.....
        ......fffcdb1bc111cf....
        ....fc111cbfbf1b1b1f....
        ....f1b1b1ffffbfbfbf....
        ....fbfbfffffff.........
        .........fffff..........
        ..........fff...........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .....ffff111111bf.......
        ....fc111cdb1bdfff......
        ....f1b1bcbfbfc111cf....
        ....fbfbfbffff1b1b1f....
        .........fffffffbfbf....
        ..........fffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `],
    500,
    true
    )
})
scene.onOverlapTile(SpriteKind.Enemy, sprites.dungeon.floorLight3, function (sprite, location) {
    desalmado.vy = 250
    desalmado = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fd11111111df......
        ......fbd111111dbf......
        ......fcd111111dcf......
        .......fb111111bf.......
        ......fffcd11dcffff.....
        ....fc111cbddbc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleRedCrystal, function (sprite, location) {
    level_atual += 1
    avancarlevel(1)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.stairLarge, function (sprite, location) {
    level_atual += 1
    avancarlevel(2)
})
let desalmado: Sprite = null
let ameba: Sprite = null
ameba = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . f f f f f f . . . . . . 
    . . . f f 1 1 1 1 f f . . . . . 
    . . f f 1 1 1 1 1 1 f . . . . . 
    . . f f 1 f f 1 f f 1 . . 1 1 . 
    . f f f 1 f f 1 f f 1 . . e . 1 
    . f f f 1 1 1 1 1 1 f . . e . . 
    . f f f f f 1 1 f 1 f . . e . . 
    . f . f f f f f f f . . e . . . 
    . . . f f f f f f f f f e . . . 
    . . f f f f f f f f f f f . . . 
    . . f f f f f f f f . f f . . . 
    . . . . f f f f f f . e . . . . 
    . . . . f f . . f f . e . . . . 
    `, SpriteKind.Player)
controller.moveSprite(ameba)
scene.setBackgroundColor(11)
scene.cameraFollowSprite(ameba)
let level_atual = 0
avancarlevel(1)
multilights.addLightSource(ameba, 8)
game.onUpdate(function () {
    for (let value of sprites.allOfKind(SpriteKind.Enemy)) {
        if (true) {
        	
        }
    }
})
game.onUpdateInterval(5000, function () {
    for (let valor2 of tiles.getTilesByType(assets.tile`myTile`)) {
        desalmado = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, SpriteKind.Enemy)
        animation.runImageAnimation(
        desalmado,
        [img`
            . . . . . . f f f f f . . . . . 
            . . . . f f 1 1 1 1 1 f . . . . 
            . . . f b 1 1 1 1 1 1 b f . . . 
            . . f b d 1 1 1 1 1 1 1 f . . . 
            . . f d d d 1 1 1 1 1 1 d f . . 
            . . f d d d d 1 1 1 1 1 d f . . 
            . . f d d d d d d d 1 1 d f . . 
            . . f d d d d d d d 1 1 1 f . . 
            . . f d d d d d d c f 1 1 f . . 
            . . . f b d d d b 1 1 1 1 b f . 
            . . . . f f f c f d b 1 b 1 f . 
            . . . f f f f f f f f b f b f . 
            f f . f f f f f f f f f f f . . 
            . f f f f f f f f . . . . . . . 
            . f f f f f f b 1 b 1 f . . . . 
            . . f f f f f f b f b f . . . . 
            `,img`
            . . . . f f f f . . . . . . . . 
            . . f f 1 1 1 1 f f . . . . . . 
            . f b 1 1 1 1 1 1 b f . . . . . 
            . f d 1 1 1 1 1 1 1 f . . . . . 
            f d d 1 1 1 1 1 1 1 d f . . . . 
            f d d d 1 1 1 1 1 1 d f . . . . 
            f d d d d d d 1 1 1 d f . . . . 
            f b d d d d b f d 1 d f . . . . 
            f c b b b d c f d d b f . . . . 
            . f c b b 1 1 1 1 1 f . . . . . 
            . . f f f f f 1 b 1 f . . . . . 
            . . f b 1 1 1 c f b f . . . . . 
            . . f f b 1 b 1 f f . . . . . . 
            f . f f f b f b f . . . . . . . 
            f f f f f f f f . . . . . . . . 
            . f f f f f . . . . . . . . . . 
            `],
        500,
        true
        )
        tiles.placeOnTile(desalmado, valor2)
        desalmado.vx = 100
    }
})
